name: eye_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.1
  firebase_auth: ^0.18.2
  google_sign_in: ^4.5.6
  convex_bottom_bar: ^2.6.0
  font_awesome_flutter: ^8.10.0
  provider: ^4.3.2+2
  permission_handler: ^5.0.1+1
  firebase_messaging: ^7.0.3
  device_apps: ^1.2.0
  cloud_firestore: ^0.14.3
  image_picker: ^0.6.7+15
  firebase_core: ^0.5.3
  path_provider: ^1.6.24
  firebase_ml_vision: ^0.9.10
  fluttertoast: ^7.1.6
  fl_chart: ^0.12.2
  uuid: ^2.2.2
  firebase_storage: ^4.0.0
  flutter_screenutil: ^4.0.2+2
  line_awesome_flutter: ^1.0.1
  app_usage: ^1.1.1
  algolia: ^0.1.7
  flutter_bloc: ^6.1.1
  equatable: ^1.1.1
  bloc: ^6.1.1
  charts_flutter: ^0.9.0
  wave: ^0.0.8
  data_connection_checker: ^0.3.4
  easy_localization: ^2.3.0
  pedantic: ^1.9.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/png/
    - assets/
    - assets/Apps/
    - assets/Social/
    - assets/fonts/
    - resources/langs/en-US.json
    - resources/langs/tr-TR.json
    - resources/langs/fr-FR.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: CustomIcons
       fonts:
         - asset: assets/fonts/CustomIcons.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
